title: ML Interview Blogs
description: AI / ML / LLM Interview Questions
url: "https://ayush1298.github.io"
baseurl: "/ML-Interview-Based-Blogs"

markdown: kramdown
theme: jekyll-theme-minimal

exclude:
  - scripts
  - node_modules
  - Gemfile
  - Gemfile.lock

permissions:
  contents: write